mysi/Knopka/urls.py
from django.urls import path, include
from django.views.generic import ListView, DetailView
from Knopka.models import opa
from .views import *

app_name = "knopka"

urlpatterns = [
    path("", KnopkaListView.as_view(),name = "index"),
    path("<int:pk>", KnopkaDetailView.as_view(), name = "detail"),
]

mysi/firstApp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

mysi/hello/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.Hy, name='Hy'),
]

mysi/mysi/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', include('hello.urls')),
    path('knopk/', include('Knopka.urls')),
    path('', include('firstApp.urls')),
]

mysi/Knopka/models.py
from django.db import models

class opa(models.Model):
    name=models.CharField(max_length=100)
    text=models.TextField()
    date=models.DateTimeField()

def Tname(self):
    return self.name

mysi/firstApp/models.py
from django.db import models

mysi/hello/models.py
from django.db import models

# Create your models here.

mysi/Knopka/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView

from .models import opa
# Create your views here.

class KnopkaListView(ListView):
    model = opa
    queryset=opa.objects.all().order_by("-date")[:10]


class KnopkaDetailView(DetailView):
    model = opa

mysi/firstApp/views.py
from django.shortcuts import render
from django.http import HttpResponse

def index(request):
    return render(request,'shabl/fPage.html')

mysi/hello/views.py
from django.shortcuts import render
from django.http import HttpResponse

def Hy(i):
    return HttpResponse('Привет мир!!!')
# Create your views here.

mysi/Knopka/templates/Knopka/includes/new.html
{% block content %}
<p>БД</p>
{% endblock %}

mysi/Knopka/templates/Knopka/opa_list.html
{% extends "Knopka/wrapper.html" %}

{% block content %}
  {% for ity in object_list %}
    <a href="{% url "knopka:detail" pk=ity.pk %}"><h3>{{ity.name}}</h3></a>
    <p>{{ity.text}}</p>
    <h4>{{ity.date|date:"m-d-Y"}}</h4>
  {% endfor %}
{% endblock %}

mysi/Knopka/templates/Knopka/wrapper.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Start</title>
  </head>
  <body style="background: silver">
    {% include "shabl/includes/new.html" %}
        {% block content %}
        {% endblock %}
        <div>
          <a href="">Кнопка</a>
        </div>
  </body>
</html>

mysi/firstApp/templates/shabl/fPage.html
{% extends "shabl/wrapper.html" %}
{% block content %}
<p>ustal</p>

{% include "shabl/includes/new.html" %}
{% include "shabl/includes/new.html" %}
{% endblock %}

mysi/firstApp/templates/shabl/includes/new.html
{% block content %}
<p>Встроенный include</p>
{% endblock %}

mysi/firstApp/templates/shabl/wrapper.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Start</title>
  </head>
  <body style="background: silver">
    {% include "shabl/includes/new.html" %}
        {% block content %}
        {% endblock %}
        <div>
          <a href="knopka/">Кнопка</a>
        </div>
  </body>
</html>